// Capsule dock copy (P6): every user-visible string in the floating capsule.
// zh/en are complete; ja/ko fall back to English for the new dock keys and
// keep their existing translations for the original keys.

export type CapsuleLocale = 'zh' | 'en' | 'ja' | 'ko';

const en = {
  dock: 'Vesti Dock',
  liveOn: 'Live capture on',
  liveOff: 'Capture paused',
  syncing: 'Syncing…',
  conversations: 'Archived sessions',
  syncNow: 'Sync now',
  openMain: 'Open Vesti',
  pause: 'Pause capture',
  resume: 'Resume capture',
  hide: 'Hide floating ball',
  menuOpen: 'Open Vesti',
  menuSync: 'Sync now',
  menuWatching: 'Live capture',
  menuHide: 'Hide floating ball',
  // Home status line
  statusSources: 'sources',
  statusLive: 'live',
  statusPaused: 'paused',
  // Quick ask
  quickAskPlaceholder: 'Ask about your sessions…',
  quickAskDisabledHint: 'Configure an LLM in Settings first',
  quickAskLoading: 'Thinking…',
  quickAskRecalled: '{n} sessions recalled',
  quickAskFailed: 'Ask failed',
  quickAskModel: 'Model',
  quickAskModelHints: {
    'qwen-plus': 'default · balanced',
    'qwen-turbo': 'fastest',
    'qwen-max': 'strongest Qwen',
    'deepseek-v3': 'balanced all-round',
    'deepseek-r1': 'deep reasoning · slow',
  },
  quickAskModelCustomPlaceholder: 'Model id your key can access…',
  quickAskModelRecommend: 'Suggested',
  quickAskModelNew: 'new',
  quickAskModelV4FlashNote: 'New on Bailian — your key must support it',
  copy: 'Copy',
  collapse: 'Collapse',
  // Shared
  back: 'Back',
  cancel: 'Cancel',
  next: 'Next',
  copied: 'Copied — Ctrl+V in the target window',
  copiedPlain: 'Copied',
  sendToBrowser: 'Send to browser',
  sentToBrowser: 'Queued for the browser extension',
  browserNotConnected: 'No browser extension connected',
  actionFailed: 'Action failed',
  // AI relay flow
  relay: 'AI Relay',
  relayScopeTitle: 'Pick a handoff scope',
  relayProjectEmpty: 'No projects yet — sync your sessions first',
  relaySessionsUnit: 'sessions',
  relaySessionPick: 'Narrow to sessions (optional)',
  relayWholeProject: 'Whole project',
  relayBuild: 'Build draft',
  relayPreviewTitle: 'Compressed preview',
  relayPreviewNote: 'Assembled locally from digests — no AI involved yet.',
  relayPolish: 'AI polish',
  relayPolishing: 'Polishing…',
  relayEdit: 'Edit',
  relayEditTitle: 'Edit the injection text',
  relayChars: '{n} chars',
  relayDeliver: 'Continue to inject',
  relayDeliverTitle: 'Inject',
  deliverCopy: 'Copy to clipboard',
  deliverCli: 'Generate CLI command',
  // Prompt assistant
  prompts: 'Prompt Assistant',
  promptSearchPlaceholder: 'Search prompts…',
  promptEmpty: 'No matching prompts',
  promptNoSnapshot: 'Personal library empty — showing curated catalog only',
  promptFromCurated: 'Curated',
  promptFromUser: 'Mine',
  // Prompt refine / continue (LLM)
  promptImprove: 'Improve',
  promptContinue: 'Continue',
  promptImproving: 'Improving…',
  promptContinuing: 'Continuing…',
  promptLlmRequired: 'Configure an LLM in Settings first',
  promptImproveNotes: 'What changed',
  promptUseResult: 'Use this version',
  // Prompt editing + natural-language refine
  promptEditTitle: 'Edit prompt text',
  promptRevert: 'Restore original',
  promptUndo: 'Undo last version',
  promptRefinePlaceholder: 'Describe how to improve… e.g. "tighter", "aim it at code review"',
  promptRefineSubmit: 'Refine as described',
};

export type CapsuleCopy = typeof en;

const zh: CapsuleCopy = {
  dock: 'Vesti Dock',
  liveOn: '实时采集中',
  liveOff: '采集已暂停',
  syncing: '正在同步…',
  conversations: '已归档会话',
  syncNow: '立即同步',
  openMain: '打开主界面',
  pause: '暂停采集',
  resume: '恢复采集',
  hide: '隐藏悬浮球',
  menuOpen: '打开 Vesti',
  menuSync: '立即同步',
  menuWatching: '实时采集',
  menuHide: '隐藏悬浮球',
  statusSources: '采集点',
  statusLive: '实时采集',
  statusPaused: '已暂停',
  quickAskPlaceholder: '快速提问…',
  quickAskDisabledHint: '请先在设置中配置 LLM',
  quickAskLoading: '正在思考…',
  quickAskRecalled: '参考 {n} 个会话',
  quickAskFailed: '提问失败',
  quickAskModel: '模型',
  quickAskModelHints: {
    'qwen-plus': '默认 · 均衡',
    'qwen-turbo': '最快',
    'qwen-max': '通义最强',
    'deepseek-v3': '均衡全能',
    'deepseek-r1': '深度推理 · 较慢',
  },
  quickAskModelCustomPlaceholder: '输入你的 Key 可用的模型 ID…',
  quickAskModelRecommend: '推荐',
  quickAskModelNew: '新',
  quickAskModelV4FlashNote: '百炼新模型，需你的 Key 支持',
  copy: '复制',
  collapse: '收起',
  back: '返回',
  cancel: '取消',
  next: '下一步',
  copied: '已复制，到目标窗口 Ctrl+V',
  copiedPlain: '已复制',
  sendToBrowser: '发送到浏览器',
  sentToBrowser: '已发送到浏览器扩展',
  browserNotConnected: '未连接浏览器扩展',
  actionFailed: '操作失败',
  relay: 'AI 接力',
  relayScopeTitle: '选择交接范围',
  relayProjectEmpty: '暂无项目，请先同步会话',
  relaySessionsUnit: '个会话',
  relaySessionPick: '勾选会话（可选）',
  relayWholeProject: '整个项目',
  relayBuild: '生成草稿',
  relayPreviewTitle: '压缩预览',
  relayPreviewNote: '由本地索引摘要拼装，未经 AI 压缩。',
  relayPolish: 'AI 精简',
  relayPolishing: 'AI 精简中…',
  relayEdit: '编辑',
  relayEditTitle: '编辑注入文本',
  relayChars: '{n} 字',
  relayDeliver: '去注入',
  relayDeliverTitle: '注入',
  deliverCopy: '复制到剪贴板',
  deliverCli: '生成 CLI 命令',
  prompts: '提示词助手',
  promptSearchPlaceholder: '搜索提示词…',
  promptEmpty: '没有匹配的提示词',
  promptNoSnapshot: '个人提示词库为空，当前仅显示策展目录',
  promptFromCurated: '策展',
  promptFromUser: '我的',
  promptImprove: '优化',
  promptContinue: '续写',
  promptImproving: '优化中…',
  promptContinuing: '续写中…',
  promptLlmRequired: '请先在设置中配置 LLM',
  promptImproveNotes: '修改要点',
  promptUseResult: '使用此版本',
  promptEditTitle: '编辑提示词文本',
  promptRevert: '恢复原稿',
  promptUndo: '回退上一版',
  promptRefinePlaceholder: '描述想怎么优化，如「更简洁」「改成面向代码审查」…',
  promptRefineSubmit: '按描述优化',
};

/** ja/ko keep their legacy translations; new dock keys fall back to English. */
export const COPY: Record<CapsuleLocale, CapsuleCopy> = {
  zh,
  en,
  ja: {
    ...en,
    dock: 'Vesti Dock',
    liveOn: 'リアルタイム収集中',
    liveOff: '収集を一時停止中',
    syncing: '同期中…',
    conversations: 'アーカイブ済み会話',
    syncNow: '今すぐ同期',
    openMain: 'メイン画面を開く',
    pause: '収集を一時停止',
    resume: '収集を再開',
    hide: 'フローティングボールを隠す',
    menuOpen: 'Vesti を開く',
    menuSync: '今すぐ同期',
    menuWatching: 'リアルタイム収集',
    menuHide: 'フローティングボールを隠す',
    quickAskModel: 'モデル',
    quickAskModelHints: {
      'qwen-plus': 'デフォルト · バランス',
      'qwen-turbo': '最速',
      'qwen-max': 'Qwen 最上位',
      'deepseek-v3': 'バランス型',
      'deepseek-r1': '深い推論 · 低速',
    },
    quickAskModelCustomPlaceholder: '利用可能なモデル ID を入力…',
    quickAskModelRecommend: 'おすすめ',
    quickAskModelNew: '新着',
    quickAskModelV4FlashNote: 'Bailian の新モデル — お使いのキーでの対応が必要です',
    promptEditTitle: 'プロンプト本文を編集',
    promptRevert: '原本に戻す',
    promptUndo: '前のバージョンに戻す',
    promptRefinePlaceholder: '改善の方向を入力（例:「もっと簡潔に」「コードレビュー向けに」）…',
    promptRefineSubmit: '指示どおりに改善',
  },
  ko: {
    ...en,
    dock: 'Vesti Dock',
    liveOn: '실시간 수집 중',
    liveOff: '수집 일시 중지됨',
    syncing: '동기화 중…',
    conversations: '보관된 대화',
    syncNow: '지금 동기화',
    openMain: '메인 화면 열기',
    pause: '수집 일시 중지',
    resume: '수집 재개',
    hide: '플로팅 볼 숨기기',
    menuOpen: 'Vesti 열기',
    menuSync: '지금 동기화',
    menuWatching: '실시간 수집',
    menuHide: '플로팅 볼 숨기기',
    quickAskModel: '모델',
    quickAskModelHints: {
      'qwen-plus': '기본 · 균형',
      'qwen-turbo': '가장 빠름',
      'qwen-max': '가장 강력한 Qwen',
      'deepseek-v3': '균형형',
      'deepseek-r1': '심층 추론 · 느림',
    },
    quickAskModelCustomPlaceholder: '사용 가능한 모델 ID 입력…',
    quickAskModelRecommend: '추천',
    quickAskModelNew: '신규',
    quickAskModelV4FlashNote: 'Bailian 신모델 — 사용 중인 키의 지원이 필요합니다',
    promptEditTitle: '프롬프트 본문 편집',
    promptRevert: '원본 복원',
    promptUndo: '이전 버전으로 되돌리기',
    promptRefinePlaceholder: '개선 방향을 입력하세요 (예: "더 간결하게", "코드 리뷰용으로")…',
    promptRefineSubmit: '입력한 대로 개선',
  },
};

export function formatCopy(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce(
    (text, [key, value]) => text.replace(`{${key}}`, String(value)),
    template,
  );
}
